config:
    # IDs & paths
    data_id: "exp_not_norm"
    model_id: "gan_pretrained"
    models_dir: "../trained_models/exp_gan/"
    pretrained_generator: "../trained_models/exp_gan/generator_vae"
    cosmic_version: "v3"

    # Training params
    iterations: 1000
    num_classes: 72
    batch_size: 20
    lr_generator: 0.0002
    lr_discriminator: 0.0002

    # WANDB params
    enable_logging: True
    wandb_project_id: "gan"

    # Network params
    generator_num_hidden_layers: 3
    discriminator_num_hidden_layers: 2
    latent_dim: 40  # must be the same as the pre-trained one

    # Misc
    device: "cuda"