config:
    # IDs & paths
    data_id: "datasets/errorfinder"
    model_id: "errorfinder_final"
    classifier_id: "detector"
    finetuner_low_id: "finetuner_low"
    finetuner_large_id: "finetuner_large"
    models_dir: "trained_models"

    # Training params
    # source: "realistic_low"
    iterations: 10
    num_classes: 72
    batch_size: 100
    lr: 0.000908
    sigmoid_params: [1000,200]
    loss_params: 
        lagrange_base: 0.1
        lagrange_high_error_sigs: 0.5
        lagrange_pnorm: 33434.0
        lagrange_smalltozero: 0.276
        pnorm_order: 5.0

    # WANDB params
    enable_logging: True
    wandb_project_id: "errorfinder_bayesian_lambdas"

    # Network params
    num_hidden_layers_pos: 1
    num_neurons_pos: 500
    num_hidden_layers_neg: 2
    num_neurons_neg: 500

    # Misc
    device: "cuda"
