config:
    # IDs & paths
    data_id: "exp_classifier"
    model_id: "classifier_bayesian"
    models_dir: "../trained_models"

    # Training params
    iterations: 30
    num_classes: 72
    sigmoid_params: [5000,1000]
    batch_size: 500
    lr: 0.0001

    # WANDB params
    enable_logging: True
    wandb_project_id: "classifier_bayesian"

    # Network params
    num_hidden_layers: 2
    num_neurons: 300

    # Misc
    device: "cpu"