config:
    # IDs & paths
    data_id: "exp_0"
    model_id: "exp_errorfiner_loss/test_0"
    finetuner_id: "exp_2_nets/finetuner_realistic"
    models_dir: "../trained_models"

    # Training params
    source: "mixed"
    iterations: 1
    num_classes: 72
    batch_size: 500
    lr: 0.0001
    loss_params: 
        lagrange_missclassification: 7.e-3
        lagrange_pnorm: 1.e+4
        lagrange_smalltozero: 1.0
        pnorm_order: 5.0

    # WANDB params
    enable_logging: True
    wandb_project_id: "errorfinder"

    # Network params
    num_hidden_layers_pos: 2
    num_neurons_pos: 1000
    num_hidden_layers_neg: 2
    num_neurons_neg: 1000

    # Misc
    device: "cuda"