config:
    # IDs & paths
    data_id: "exp_final"
    model_id: "errorfinder_random"
    finetuner_low_id: "finetuner_random_low"
    finetuner_large_id: "finetuner_random_large"
    models_dir: "../trained_models/exp_final"

    # Training params
    source: "random_low"
    iterations: 20
    num_classes: 72
    batch_size: 500
    lr: 0.0001
    sigmoid_params: [500,150]
    # sigmoid_params: [50000, 10000]
    loss_params: 
        lagrange_missclassification: 7e-3
        lagrange_pnorm: 1e4
        lagrange_smalltozero: 1.0
        pnorm_order: 5.0

    # WANDB params
    enable_logging: True
    wandb_project_id: "errorfinder"

    # Network params
    num_hidden_layers_pos: 2
    num_neurons_pos: 1000
    num_hidden_layers_neg: 2
    num_neurons_neg: 1000

    # Misc
    device: "cpu"