config:
    # IDs & paths
    data_id: "exp_final"
    model_id: "errorfinder_realistic_low_02"
    finetuner_low_id: "finetuner_realistic_low"
    finetuner_large_id: "finetuner_realistic_large"
    models_dir: "../trained_models/exp_final"

    # Training params
    source: "realistic_low"
    iterations: 5
    num_classes: 72
    batch_size: 500
    lr: 0.0001
    loss_params: 
        lagrange_missclassification: 1e-1
        lagrange_pnorm: 1e4
        lagrange_smalltozero: 0
        pnorm_order: 5.0

    # WANDB params
    enable_logging: True
    wandb_project_id: "errorfinder"

    Clau
    # Network params
    num_hidden_layers_pos: 2
    num_neurons_pos: 1000
    num_hidden_layers_neg: 2
    num_neurons_neg: 1000

    # Misc
    device: "cpu"