config:
    # IDs & paths
    data_id: "exp_v2"
    model_id: "finetuner_realistic_low_v2_03"
    models_dir: "../trained_models/exp_v2"

    # Training params
    source: "realistic_low"
    network_type: "realistic"
    iterations: 15
    num_classes: 30
    sigmoid_params: [500,150]
    # sigmoid_params: [50000, 10000]
    batch_size: 500
    lr: 0.0015

    # WANDB params
    enable_logging: True
    wandb_project_id: "finetuner_realistic"

    # Network params
    num_hidden_layers: 3
    num_neurons: 200

    # Misc
    device: "cuda"