config:
    # IDs & paths
    data_id: "exp_v2"
    model_id: "finetuner_cosmicv2"
    models_dir: "../trained_models"

    # Training params
    source: "random"
    network_type: "random"
    iterations: 50
    num_classes: 30
    sigmoid_params: [500,150]
    batch_size: 500
    lr: 0.0001

    # WANDB params
    enable_logging: True
    wandb_project_id: "finetuner_cosmicv2"

    # Network params
    num_hidden_layers: 2
    num_neurons: 600

    # Misc
    device: "cuda"