config:
    # IDs & paths
    data_id: "exp_final"
    model_id: "finetuner_bayesian"
    models_dir: "../trained_models"

    # Training params
    source: "realistic_low"
    network_type: "realistic"
    iterations: 30
    num_classes: 72
    sigmoid_params: [500,150]
    batch_size: 500
    lr: 0.0001

    # WANDB params
    enable_logging: True
    wandb_project_id: "finetuner_bayesian"

    # Network params
    num_hidden_layers: 2
    num_neurons: 600

    # Misc
    device: "cpu"