config:
    # IDs & paths
    data_id: "exp_final"
    model_id: "finetuner_random"
    models_dir: "../trained_models"

    # Training params
    source: "random_low"
    network_type: "random"
    iterations: 70
    num_classes: 72
    sigmoid_params: [500,150]
    batch_size: 283
    lr: 0.0015

    # WANDB params
    enable_logging: True
    wandb_project_id: "finetuner_random"

    # Network params
    num_hidden_layers: 3
    num_neurons: 50

    # Misc
    device: "cpu"