config:
    # IDs & paths
    data_id: "exp_good/generator"
    model_id: "generator"
    models_dir: "../trained_models/exp_good/"

    # Training params
    iterations: 500
    num_classes: 72
    lagrange_param: 0.001
    batch_size: 100
    lr_encoder: 0.005
    lr_decoder: 0.0005

    # WANDB params
    enable_logging: True
    wandb_project_id: "generator-clau-12"

    # Network params
    num_hidden_layers: 5
    latent_dim: 15

    # Misc
    device: "cuda"