config:
    # IDs & paths
    data_id: "exp_not_norm"
    model_id: "generator_not_norm_1"
    models_dir: "../trained_models/exp_not_norm/"
    cosmic_version: "v3"

    # Training params
    iterations: 700
    num_classes: 72
    lagrange_param: 0.001
    batch_size: 70
    lr_encoder: 0.005
    lr_decoder: 0.0005

    # WANDB params
    enable_logging: True
    wandb_project_id: "generator_not_norm"

    # Network params
    num_hidden_layers: 6
    latent_dim: 100

    # Misc
    device: "cuda"