config:
    # IDs & paths
    data_id: "real_data"
    model_id: "oversampled_dotdist_largelatent_generator_5_120_3"
    models_dir: "../trained_models/fig_generator/"
    cosmic_version: "v3"
    type: "real"

    # Training params
    iterations: 3000
    num_classes: 72
    lagrange_param: 0.00001
    batch_size: 200
    lr_encoder: 0.001
    lr_decoder: 0.0001

    # WANDB params
    enable_logging: True
    wandb_project_id: "fix_generator"

    # Network params
    num_hidden_layers: 3
    latent_dim: 120

    # Misc
    device: "cuda"