config:
    # IDs & paths
    data_id: "exp_good/generator"
    model_id: "generator"
    models_dir: "../trained_models/exp_good/"

    # Training params
    iterations: 100
    num_classes: 72
    lagrange_param: 0.
    batch_size: 100
    lr: 0.01

    # WANDB params
    enable_logging: True
    wandb_project_id: "generator"

    # Network params
    num_hidden_layers: 3
    latent_dim: 20

    # Misc
    device: "cuda"