config:
    # IDs & paths
    data_id: "exp_good/generator"
    model_id: "generator"
    models_dir: "../trained_models/exp_good/"

    # Training params
    iterations: 30
    num_classes: 72
    lagrange_param: 1.0
    batch_size: 32
    lr: 0.0001

    # WANDB params
    enable_logging: True
    wandb_project_id: "generator"

    # Network params
    num_hidden_layers: 3
    latent_dim: 5

    # Misc
    device: "cuda"