config:
   # IDs & paths
   data_id: "exp_final"
   model_id: "errorfinder_realistic_large"
   finetuner_low_id: "finetuner_realistic_low"
   finetuner_large_id: "finetuner_realistic_large"
   models_dir: "../trained_models/exp_final_2"
 
   # Training params
   source: "realistic_large"
   iterations: 20
   num_classes: 72
   batch_size: 290
   lr: 0.00055
   # sigmoid_params: [500,150]
   sigmoid_params: [50000, 10000]
   loss_params:
       lagrange_missclassification: 0.0079
       lagrange_pnorm: 92115
       lagrange_smalltozero: 3.11
       pnorm_order: 3.0
 
   # WANDB params
   enable_logging: True
   wandb_project_id: "errorfinder"
 
   # Network params
   num_hidden_layers_pos: 3
   num_neurons_pos: 1223
   num_hidden_layers_neg: 1
   num_neurons_neg: 1182
 
   # Misc
   device: "cuda"