config:
    # IDs & paths
    data_id: "exp_final"
    model_id: "errorfinder_realistic_low"
    finetuner_id: "finetuner_realistic_low"
    models_dir: "../trained_models/exp_final"

    # Training params
    source: "realistic_low"
    iterations: 20
    num_classes: 72
    batch_size: 720
    lr: 0.00001
    loss_params: 
        lagrange_missclassification: 0.005
        lagrange_pnorm: 1000
        lagrange_smalltozero: 0.1
        pnorm_order: 3.0

    # WANDB params
    enable_logging: True
    wandb_project_id: "errorfinder_final"

    # Network params
    num_hidden_layers_pos: 10
    num_neurons_pos: 528
    num_hidden_layers_neg: 4
    num_neurons_neg: 1435

    # Misc
    device: "cpu"
