config:
    # IDs & paths
    data_id: "exp_good"
    model_id: "errorfinder_perturbed"
    classifier_id: "classifier"
    finetuner_realistic_low_id: "finetuner_realistic_low"
    finetuner_realistic_large_id: "finetuner_realistic_large"
    finetuner_random_low_id: "finetuner_perturbed_low"
    finetuner_random_large_id: "finetuner_perturbed_large"
    models_dir: "../trained_models/exp_good"

    # Training params
    # source: "realistic_low"
    iterations: 10
    num_classes: 72
    batch_size: 500
    lr: 0.0001
    sigmoid_params: [1000,200]
    # sigmoid_params: [50000, 10000]
    loss_params: 
        lagrange_missclassification: 7e-3
        lagrange_pnorm: 1e4
        lagrange_smalltozero: 1e-3
        pnorm_order: 5.0

    # WANDB params
    enable_logging: True
    wandb_project_id: "errorfinder"

    # Network params
    num_hidden_layers_pos: 3
    num_neurons_pos: 1000
    num_hidden_layers_neg: 3
    num_neurons_neg: 1000

    # Misc
    device: "cuda"
