config:
    # IDs & paths
    data_id: "exp_final"
    model_id: "finetuner_random_low"
    models_dir: "../trained_models/exp_final_2"

    # Training params
    source: "random_low"
    network_type: "random"
    iterations: 30
    num_classes: 72
    sigmoid_params: [500,150]
    batch_size: 227
    lr: 0.0002

    # WANDB params
    enable_logging: True
    wandb_project_id: "finetuner_random"

    # Network params
    num_hidden_layers: 1
    num_neurons: 713

    # Misc
    device: "cuda"