config:
    # IDs & paths
    data_id: "exp_real_data"
    model_id: "finetuner_perturbed_low"
    models_dir: "../trained_models/exp_real_data"

    # Training params
    source: "perturbed_low"
    network_type: "low"
    iterations: 100
    num_classes: 72
    sigmoid_params: [[500, 150], [5000, 1000], [10000, 5000]]
    batch_size: 283
    lr: 0.0015

    # WANDB params
    enable_logging: True
    wandb_project_id: "finetuner_real_data"

    # Network params
    num_hidden_layers: 4
    num_neurons: 150

    # Misc
    device: "cuda"