config:
    # IDs & paths
    data_id: "exp_not_norm"
    model_id: "finetuner_not_norm_large"
    models_dir: "../trained_models/exp_not_norm"

    # Training params
    source: "generator_large"
    network_type: "large"
    iterations: 100
    num_classes: 72
    sigmoid_params: [50000, 10000]
    batch_size: 500
    lr: 0.0005

    # WANDB params
    enable_logging: True
    wandb_project_id: "finetuner_generator_not_norm"

    # Network params
    num_hidden_layers: 2
    num_neurons: 300

    # Misc
    device: "cuda"