config:
    # IDs & paths
    data_id: "exp_not_norm/sd1.5"
    model_id: "model_id"
    models_dir: "../trained_models/ensemble"

    # Training params
    source: "generator_large"
    network_type: "large"
    iterations: 30
    num_classes: 72
    sigmoid_params: [[1000, 1000], [10000, 2000], [100000, 5000]]
    batch_size: 500
    lr: 0.0005

    # WANDB params
    enable_logging: True
    wandb_project_id: "finetuner_ensemble"

    # Network params
    num_hidden_layers: 2
    num_neurons: 300

    # Misc
    device: "cuda"