config:
    # IDs & paths
    data_id: "exp_oversample"
    model_id: "finetuner_oversample_bayesian_large"
    models_dir: "../trained_models/exp_oversample_bayesian"
    load_data: True
    
    # Training params
    source: "large"
    network_type: "large"
    iterations: 1000
    num_classes: 72
    sigmoid_params: [50000, 10000]
    batch_size: 500
    lr: 0.0005

    # WANDB params
    enable_logging: True
    wandb_project_id: "exp_oversample_bayesian_low"

    # Network params
    num_hidden_layers: 2
    num_neurons: 300

    # Misc
    device: "cuda"