config:
    # IDs & paths
    data_id: "exp_generator"
    model_id: "finetuner_generator_low"
    models_dir: "../trained_models/exp_generator"

    # Training params
    source: "generator_low"
    network_type: "low"
    iterations: 400
    num_classes: 72
    sigmoid_params: [500,150]
    batch_size: 500
    lr: 0.00005

    # WANDB params
    enable_logging: True
    wandb_project_id: "finetuner_generator_split"

    # Network params
    num_hidden_layers: 1
    num_neurons: 200

    # Misc
    device: "cuda"