config:
    # IDs & paths
    data_id: "exp_good"
    model_id: "finetuner_perturbed_large"
    models_dir: "../trained_models/exp_good"

    # Training params
    source: "perturbed_large"
    network_type: "perturbed"
    iterations: 30
    num_classes: 72
    sigmoid_params: [50000, 10000]
    batch_size: 227
    lr: 0.0002

    # WANDB params
    enable_logging: True
    wandb_project_id: "finetuner_perturbed"

    # Network params
    num_hidden_layers: 1
    num_neurons: 713

    # Misc
    device: "cuda"