config:
    # IDs & paths
    data_id: "exp_real_data"
    model_id: "finetuner_perturbed_large"
    models_dir: "../trained_models/exp_real_data"

    # Training params
    source: "perturbed_large"
    network_type: "large"
    iterations: 1000
    num_classes: 72
    sigmoid_params: [50000, 10000]
    batch_size: 500
    lr: 0.0005

    # WANDB params
    enable_logging: True
    wandb_project_id: "finetuner_real_data"

    # Network params
    num_hidden_layers: 2
    num_neurons: 300

    # Misc
    device: "cuda"